# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)

In [15]:
print(A)
print()
print("Number of axes:", A.ndim)
print("Shape:", A.shape)
print("Size:", A.size)
print("Datatype:", A.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Number of axes: 2
Shape: (3, 5)
Size: 15
Datatype: int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [16]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [20]:
subtraction = B-C
print("Elementwise subtraction:")
print(subtraction)
print()

multiplication = B*C
print("Elementwise multiplication:")
print(multiplication)
print()

matrix = B@C
print("Matrix multiplication:")
print(matrix)

Elementwise subtraction:
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise multiplication:
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix multiplication:
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [21]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
exponentiate = np.exp(B)
print("Exponentiate each number:")
print(exponentiate)
print()

minValue = np.min(B)
print("Minimum value of matrix:")
print(minValue)
print()

minValRow = np.min(B, axis=0)
print("Minimum value of each row:")
print(minValRow)
print()

minValCol = np.min(B, axis=1)
print("Minimum value of each column:")
print(minValCol)
print()

indexValue = np.argmin(B)
print("Minimum index value of matrix:")
print(indexValue)
print()

indexValRow = np.argmin(B, axis=0)
print("Minimum index value of each row:")
print(indexValRow)
print()

sumMatrix = np.sum(B)
print("Sum of all elements in matrix:")
print(sumMatrix)
print()

meanCol = np.mean(B, axis=1)
print("Mean of each column:")
print(meanCol)
print()

medianCol = np.median(B, axis=1)
print("Median of each column:")
print(medianCol)
print()

Exponentiate each number:
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value of matrix:
1

Minimum value of each row:
[1 4 7]

Minimum value of each column:
[1 2 3]

Minimum index value of matrix:
0

Minimum index value of each row:
[0 0 0]

Sum of all elements in matrix:
45

Mean of each column:
[4. 5. 6.]

Median of each column:
[4. 5. 6.]



### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [35]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [34]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [38]:
"""You will get a subdimensional array and it leaves the rest of the array unspecified."""
print(__doc__)

You will get a subdimensional array and it leaves the rest of the array unspecified.


### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [39]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [53]:
for i in A:
    for x in i:
        print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [58]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [63]:
"""A is an one dimensional array with 30 elements, while B is a 3D array. The 2 means that it will be two 
blocks/subarrays, the 3 gives the arrays 3 rows each and -1 lets numpy set the number of columns to fit with 
all the elements in A. The -1 could also be a 5 and the arrays would look the same."""
print(__doc__)

A is an one dimensional array with 30 elements, while B is a 3D array. The 2 means that it will be two 
blocks/subarrays, the 3 gives the arrays 3 rows each and -1 lets numpy set the number of columns to fit with 
all the elements in A. The -1 could also be a 5 and the arrays would look the same.


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [70]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)
print()
print(m1.shape)
print(m2.shape)

[[2 3]
 [4 5]]

(2, 2)
(2,)


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [65]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [94]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)
print()
print(A+b)

[[1 2]
 [3 4]]
[2 2]

[[3 4]
 [5 6]]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [95]:
MA = np.array([[2, 1, -1], [1, -1, 1]])
MB = np.array([[4, -2, 1], [2, -4, -2]])

MC = np.array([[1, 2], [2, 1]])
MD = np.array([[3, 4], [4, 3]])

ME = np.array([[1], [2]])

print(MA)
print(MB)
print(MC)
print(MD)
print(ME)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [84]:
def add_mult_matrices(MA, MB, action):
    if not (isinstance(MA, np.ndarray) and isinstance(MB, np.ndarray)):
            raise ValueError("Both matrices needs to be the same type of array.")
    
    if action not in ['add', 'multiply']:
            raise ValueError("You can only use add or multiply with this function.")
            
    if action == 'add':
            if MA.shape != MB.shape:
                raise ValueError("Matrices needs to have the same shape for addition.")
            else:
                return MA + MB
    
    elif action == 'multiply':
            if MA.shape[1] != MB.shape[0]:
                raise ValueError("The sizes does not comply to multiplication.")
            else:
                return MA @ MB

In [101]:
add_mult_matrices(MB, -2*MA, 'add')

array([[ 0, -4,  3],
       [ 0, -2, -4]])

In [102]:
add_mult_matrices(3*MC, -ME, 'add')

ValueError: Matrices needs to have the same shape for addition.

In [103]:
add_mult_matrices(MA, MC, 'multiply')

ValueError: The sizes does not comply to multiplication.

In [104]:
add_mult_matrices(MC, MD, 'multiply')

array([[11, 10],
       [10, 11]])

In [105]:
add_mult_matrices(MC, MB, 'multiply')

array([[  8, -10,  -3],
       [ 10,  -8,   0]])

**Chap2. Question 2**

In [106]:
MA1 = np.array([[1, 2], [2, 4]])
MB1 = np.array([[2, 1], [1, 3]])
MC1 = np.array([[4, 3], [0, 2]])

In [110]:
MA1MB1 = add_mult_matrices(MA1, MB1, 'multiply')
MA1MC1 = add_mult_matrices(MA1, MC1, 'multiply')

print(MA1MB1)
print()
print(MA1MC1)
print()

print((MA1MB1 == MA1MC1).all())  
print((MB1 == MC1).all()) 

[[ 4  7]
 [ 8 14]]

[[ 4  7]
 [ 8 14]]

True
False


**Chap2. Question 3**

In [111]:
A = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 4]])
D = np.array([[2, 0, 0], [0, 3, 0], [0, 0, 4]])

In [114]:
AD = add_mult_matrices(A, D, 'multiply')
DA = add_mult_matrices(D, A, 'multiply')

print(AD)
print()
print(DA)

[[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]

[[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.11, Question 2**

In [115]:
N1 = np.array([[1, -1], [-1, 1]])
N2 = np.array([[-1, 1], [1, -1]])

In [117]:
N1N2 = add_mult_matrices(N1, N2, 'multiply')
print(N1N2)

[[-2  2]
 [ 2 -2]]


**Chap 6. Question 1**

In [120]:
N3 = np.array([[5, 6], [4, 5]])
N4 = np.array([[6, 4], [3, 3]])

new_N3 = np.linalg.inv(N3)
new_N4 = np.linalg.inv(N4)

print(new_N3)
print()
print(new_N4)

[[ 5. -6.]
 [-4.  5.]]

[[ 0.5        -0.66666667]
 [-0.5         1.        ]]


**Quiz p.19, Question 3**

In [129]:
A11 = np.array([[2, 2], [1, 2]])
A11_new = np.linalg.inv(A11)
print(A11_new)
print()
print(A11_new *2)
print()

"""The answer is A, 1/2 [2, -2], [-1, 2]."""
print(__doc__)

[[ 1.  -1. ]
 [-0.5  1. ]]

[[ 2. -2.]
 [-1.  2.]]

The answer is A, 1/2 [2, -2], [-1, 2].


**Chap10. Question 1 a)**

In [130]:
M11 = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
M12 = np.array([-7, 5, 2])
print(M11)
print()
print(M12)

[[ 3 -7 -2]
 [-3  5  1]
 [ 6 -4  0]]

[-7  5  2]


In [132]:
x = np.linalg.solve(M11, M12)
print(x)

[ 3.  4. -6.]


**Chap10. Question 1 b)**

In [135]:
A21 = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])
B22 = np.array([1, -1, 1])

print(A21)
print()
print(B22)

print()

y = np.linalg.solve(A21, B22)
print(y)

[[ 1 -2  3]
 [-1  3 -1]
 [ 2 -5  5]]

[ 1 -1  1]

[ 8.  2. -1.]


**Chap 12. Question 1**

In [137]:
V = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
print(V)
print()

V_new = np.linalg.inv(V)
print(V_new)

[[ 3 -7 -2]
 [-3  5  1]
 [ 6 -4  0]]

[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [143]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [139]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [140]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [144]:
"""The answers to this questions is written in the comments above. :)"""
print(__doc__)

The answers to this questions is written in the comments above. :)
